version: "3.9"

services:
  browser-client:
    build:
      context: ./browser-client
      dockerfile: Dockerfile
    ports:
      - '80:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    command: java -jar app.jar
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - notepad-database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  notepad-database: