version: "3.9"

services:
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - notepad-database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  notepad-database: