server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  datasource:
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    url: jdbc:postgresql://${DB_CONTAINER_NAME:localhost}:${DB_CONTAINER_PORT:5432}/${POSTGRES_DB:notepad}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
export:
  filename: export.txt
user:
  username: ${USER_USERNAME:user}
  password: ${USER_PASSWORD:pass}